name: Build Test

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-debug:
    name: Build Debug
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ubuntu-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ubuntu-cargo-registry-

      - name: Cache cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ubuntu-cargo-git-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ubuntu-cargo-git-

      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ubuntu-cargo-debug-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ubuntu-cargo-debug-

      - name: Build debug binary
        run: cargo build --verbose --all-features

      - name: Check binary size
        run: |
          ls -lh target/debug/claude-code-sync
          du -h target/debug/claude-code-sync

  build-release:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ubuntu-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ubuntu-cargo-registry-

      - name: Cache cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ubuntu-cargo-git-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ubuntu-cargo-git-

      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ubuntu-cargo-release-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ubuntu-cargo-release-

      - name: Build release binary
        run: cargo build --release --verbose

      - name: Check binary size
        run: |
          ls -lh target/release/claude-code-sync
          du -h target/release/claude-code-sync

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: claude-code-sync-binary
          path: target/release/claude-code-sync
          retention-days: 7

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo-audit
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin/cargo-audit
          key: cargo-audit-${{ runner.os }}

      - name: Install cargo-audit
        run: cargo install cargo-audit --locked

      - name: Run security audit
        run: cargo audit

  dependency-check:
    name: Dependency Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Check dependencies
        run: cargo tree

      - name: Check for outdated dependencies
        run: |
          cargo install cargo-outdated --locked
          cargo outdated --exit-code 1 || echo "Some dependencies are outdated"
