name: Integration Tests

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ubuntu-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ubuntu-cargo-registry-

      - name: Cache cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ubuntu-cargo-git-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ubuntu-cargo-git-

      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ubuntu-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ubuntu-cargo-build-

      - name: Setup git config for tests
        run: |
          git config --global user.email "ci@github.actions"
          git config --global user.name "GitHub Actions CI"

      - name: Run integration tests
        run: cargo test --test '*' --verbose

      - name: Run all tests with integration flag
        run: cargo test --verbose --all-features

  end-to-end-tests:
    name: End-to-End Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ubuntu-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ubuntu-cargo-registry-

      - name: Cache cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ubuntu-cargo-git-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ubuntu-cargo-git-

      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ubuntu-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ubuntu-cargo-build-

      - name: Setup git config
        run: |
          git config --global user.email "ci@github.actions"
          git config --global user.name "GitHub Actions CI"

      - name: Build binary
        run: cargo build --release --verbose

      - name: Test binary execution
        run: |
          ./target/release/claude-code-sync --version
          ./target/release/claude-code-sync --help
